# Required software to use the notebooks for the Info-111 course
name: info-111-notebooks

channels:
- QuantStack
- conda-forge

dependencies:
- cling
- xeus-cling
- notebook
- nbgrader
- pip:
    - ordo
