# Logiciels requis pour utiliser les documents du cours Info 111
name: info-111

channels:
- QuantStack
- conda-forge

dependencies:
- cling
- xeus-cling
- notebook
- nbgrader
- pip:
    - ordo
    - .
